### PR TITLE
Df-273: Fixing update query creation by removing empty fields

### LINKED ISSUE #273: Issues causing partial updates to clear out complex objects
There is an issue where in a UpdateInStore will clear out a complex object when another property is updated, due to the serialization of empty arrays.

### PR DESCRIPTION
**Pull request by cherrera2001**
This PR resolves #273

There was an issue when serializing an update query, that empty arrays would erroneously be sent and thus clearing DoT of any values in the complex object array. There is now a removeEmpties function in the JsonUtil class that will leverage the isEmpty method to remove those empty elements.

The Util Class has also been renamed to JsonUtil.

### CODE REVIEW

File: df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java [hunk 1]
```diff
@@ -27,6 +27,7 @@
 import com.mashape.unirest.request.HttpRequestWithBody;
 import org.json.JSONObject;
 
+import javax.json.JsonObject;
```
Comment (randypitcherii) [inline df-valve/src/main/java/com/hashmapinc/tempus/witsml/valve/dot/DotDelegator.java]: should be removed pls
